services:
     postgres:
       image: postgres:latest
       environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: person_service
       ports:
         - "6500:5432"
       volumes:
         - postgres_data:/var/lib/postgresql/data
       healthcheck:
         test: ["CMD-SHELL", "pg_isready -U postgres"]
         interval: 5s
         timeout: 5s
         retries: 5
       container_name: person-service-postgres
       command: ["postgres", "-c", "password_encryption=md5"]

volumes:
  postgres_data: